In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display plots inside Jupyter Notebook
%matplotlib inline

# Set visualization style
plt.style.use('ggplot')

# Ignore warning messages
import warnings
warnings.filterwarnings('ignore')

In [9]:
# Load dataset
df = pd.read_csv("KADIRS_Tax_Compliance_2000_Rows.csv")

In [10]:
# Display first five rows
df.head()

,record_id,taxpayer_id,tin,business_name,owner_name,taxpayer_type,business_sector,lga,registration_date,tax_year,...,payment_method,payment_date,audit_status,audit_result,penalty,annual_turnover,risk_level,compliance_score,revenue_office,notification_sent
0,1,100251,KAD-TIN-202500000,Robinson and Sons,Kayla May,Individual,ICT,Igabi,23/11/2024,2025,...,Portal,18/02/2025,Audited,No Issue,57314,126908867,High,97,Kaduna North,Yes
1,2,100226,KAD-TIN-202500001,"Conrad, Colon and Wilson",Haley Lewis,SME,Healthcare,Kaduna North,01/01/2025,2025,...,Portal,17/01/2026,Not Audited,No Issue,56443,411897789,Medium,33,Kaduna North,No
2,3,100045,KAD-TIN-202500002,Davidson LLC,Barbara Buckley,Corporate,Manufacturing,Makarfi,19/02/2024,2025,...,NGN,10/10/2024,Audited,Pending,18233,26601779,High,49,Kaduna South,Yes
3,4,100285,KAD-TIN-202500003,Burch-Waller,Jon Smith,SME,Agriculture,Jaba,13/03/2025,2025,...,NGN,11/08/2025,Audited,Pending,191136,133431865,Low,79,Kaduna South,No
4,5,100333,KAD-TIN-202500004,"Alvarez, Rodriguez and Bennett",Amanda Gonzalez,Individual,ICT,Chikun,18/04/2025,2025,...,NGN,12/04/2026,Audited,Pending,188196,170941402,Low,83,Kaduna South,No

In [11]:
df.tail()

,record_id,taxpayer_id,tin,business_name,owner_name,taxpayer_type,business_sector,lga,registration_date,tax_year,...,payment_method,payment_date,audit_status,audit_result,penalty,annual_turnover,risk_level,compliance_score,revenue_office,notification_sent
1995,1996,100394,KAD-TIN-202501995,"Mathews, Thornton and Young",John Carrillo,Individual,Agriculture,Kagarko,21/03/2025,2025,...,POS,14/11/2025,Audited,No Issue,60428,185439451,High,52,Kaduna South,Yes
1996,1997,100502,KAD-TIN-202501996,Freeman Ltd,Danielle Gonzales,Individual,Manufacturing,Kachia,14/03/2024,2025,...,POS,02/09/2024,Not Audited,Underpayment,16268,495022779,High,63,Kaduna South,No
1997,1998,100052,KAD-TIN-202501997,"Arroyo, Graham and Lee",Paula Williams,Individual,Healthcare,Lere,16/12/2024,2025,...,Portal,01/03/2025,Audited,Underpayment,49777,183084961,Low,29,Kaduna South,Yes
1998,1999,100170,KAD-TIN-202501998,Beasley-Duke,Andrew Meyer,SME,Retail,Kudan,13/01/2025,2025,...,Portal,12/06/2025,Audited,Pending,88456,236141516,Medium,30,Zaria,No
1999,2000,100691,KAD-TIN-202501999,"Castro, Anderson and Peters",Antonio Pierce,Individual,Manufacturing,Kaura,18/05/2024,2025,...,NGN,20/08/2024,Not Audited,Underpayment,182620,409494611,Medium,90,Kaduna North,No

In [12]:
# Number of rows and columns
df.shape

(2000, 29)

In [13]:
list(df.columns)

['record_id',
 'taxpayer_id',
 'tin',
 'business_name',
 'owner_name',
 'taxpayer_type',
 'business_sector',
 'lga',
 'registration_date',
 'tax_year',
 'tax_month',
 'tax_type',
 'filing_due_date',
 'filing_date',
 'filing_status',
 'amount_assessed',
 'amount_paid',
 'outstanding_balance',
 'payment_status',
 'payment_method',
 'payment_date',
 'audit_status',
 'audit_result',
 'penalty',
 'annual_turnover',
 'risk_level',
 'compliance_score',
 'revenue_office',
 'notification_sent']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            2000 non-null   int64
 1   taxpayer_id          2000 non-null   int64
 2   tin                  2000 non-null   object
 3   business_name        2000 non-null   object
 4   owner_name           2000 non-null   object
 5   taxpayer_type        2000 non-null   object
 6   business_sector      2000 non-null   object
 7   lga                  2000 non-null   object
 8   registration_date    2000 non-null   object
 9   tax_year             2000 non-null   int64
 10  tax_month            2000 non-null   object
 11  tax_type             2000 non-null   object
 12  filing_due_date      2000 non-null   object
 13  filing_date          1351 non-null   object
 14  filing_status        2000 non-null   object
 15  amount_assessed      2000 non-null   int64
 16  amount_paid          2000 non-null   int64
 17  outstanding_balance  2000 non-null   int64
 18  payment_status       2000 non-null   object
 19  payment_method       2000 non-null   object
 20  payment_date         2000 non-null   object
 21  audit_status         2000 non-null   object
 22  audit_result         2000 non-null   object
 23  penalty              2000 non-null   int64
 24  annual_turnover      2000 non-null   int64
 25  risk_level           2000 non-null   object
 26  compliance_score     2000 non-null   int64
 27  revenue_office       2000 non-null   object
 28  notification_sent    2000 non-null   object
dtypes: int64(9), object(20)
memory usage: 453.3+ KB

In [15]:
df.describe()

,record_id,taxpayer_id,tax_year,amount_assessed,amount_paid,outstanding_balance,penalty,annual_turnover,compliance_score
count,2000.000000,2000.000000,2000.0,2.000000e+03,2.000000e+03,2.000000e+03,2000.000000,2.000000e+03,2000.000000
mean,1000.500000,100344.825000,2025.0,2.590214e+06,1.961347e+06,6.288673e+05,99467.005000,2.526930e+08,59.616500
std,577.494589,200.586328,0.0,1.440362e+06,1.523135e+06,1.121835e+06,58012.701994,1.427763e+08,23.496733
min,1.000000,100001.000000,2025.0,5.154600e+04,3.590000e+02,0.000000e+00,15.000000,2.452751e+06,20.000000
25%,500.750000,100167.750000,2025.0,1.348322e+06,5.783630e+05,0.000000e+00,48284.750000,1.288968e+08,39.000000
50%,1000.500000,100339.500000,2025.0,2.652268e+06,1.605515e+06,0.000000e+00,98355.000000,2.488678e+08,59.000000
75%,1500.250000,100520.000000,2025.0,3.825827e+06,3.269239e+06,9.156542e+05,151123.250000,3.750891e+08,80.000000
max,2000.000000,100700.000000,2025.0,4.998164e+06,4.996304e+06,4.756206e+06,199926.000000,4.997221e+08,100.000000

In [16]:
df.describe(include='object')

,tin,business_name,owner_name,taxpayer_type,business_sector,lga,registration_date,tax_month,tax_type,filing_due_date,filing_date,filing_status,payment_status,payment_method,payment_date,audit_status,audit_result,risk_level,revenue_office,notification_sent
count,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,1351,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,2000,1918,1968,3,5,23,497,12,4,669,582,3,2,4,658,2,3,3,3,2
top,KAD-TIN-202500000,Williams Inc,Michael Castillo,Corporate,Healthcare,Igabi,25/01/2025,Sep,Road Tax,28/06/2025,17/01/2025,Filed,Paid,Portal,21/04/2025,Not Audited,Pending,Medium,Zaria,Yes
freq,1,5,4,698,414,102,12,197,536,10,9,699,1351,576,12,1020,672,681,685,1039

In [17]:
df.isnull().sum()

record_id                0
taxpayer_id              0
tin                      0
business_name            0
owner_name               0
taxpayer_type            0
business_sector          0
lga                      0
registration_date        0
tax_year                 0
tax_month                0
tax_type                 0
filing_due_date          0
filing_date            649
filing_status            0
amount_assessed          0
amount_paid              0
outstanding_balance      0
payment_status           0
payment_method           0
payment_date             0
audit_status             0
audit_result             0
penalty                  0
annual_turnover          0
risk_level               0
compliance_score         0
revenue_office           0
notification_sent        0
dtype: int64

In [18]:
missing = df.isnull().sum()

missing[missing > 0]

filing_date    649
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.sample(10)

,record_id,taxpayer_id,tin,business_name,owner_name,taxpayer_type,business_sector,lga,registration_date,tax_year,...,payment_method,payment_date,audit_status,audit_result,penalty,annual_turnover,risk_level,compliance_score,revenue_office,notification_sent
160,161,100208,KAD-TIN-202500160,Ramos-Murray,Shaun Wood,Corporate,ICT,Soba,13/08/2024,2025,...,Bank Transfer,24/05/2025,Not Audited,No Issue,97476,358755448,High,41,Kaduna North,No
1909,1910,100501,KAD-TIN-202501909,"Gibson, Reyes and Washington",Christine Delgado,SME,Manufacturing,Kauru,21/06/2024,2025,...,Portal,02/06/2025,Audited,Underpayment,146538,230248162,Low,46,Kaduna South,Yes
1861,1862,100227,KAD-TIN-202501861,"Mathis, Martinez and Swanson",Alexandra Davis,Corporate,ICT,Kajuru,26/04/2025,2025,...,Portal,18/09/2025,Audited,No Issue,191290,111792839,Medium,84,Kaduna South,No
1245,1246,100300,KAD-TIN-202501245,Johnston and Sons,Alexis Lamb,Corporate,Retail,Kachia,22/10/2024,2025,...,Bank Transfer,24/02/2025,Audited,No Issue,82940,462716662,Low,25,Kaduna North,Yes
1784,1785,100009,KAD-TIN-202501784,Jackson-Frazier,Joseph Wallace,SME,Agriculture,Kaduna South,26/06/2024,2025,...,Portal,10/06/2025,Audited,No Issue,198887,433840395,Medium,80,Zaria,No
1716,1717,100375,KAD-TIN-202501716,Bailey LLC,Sarah Gonzalez,SME,Healthcare,Soba,13/08/2024,2025,...,NGN,26/10/2024,Audited,No Issue,187983,67195003,Medium,37,Kaduna South,Yes
610,611,100311,KAD-TIN-202500610,"Powell, Boyer and Garner",Erika Monroe,SME,Agriculture,Giwa,24/09/2024,2025,...,Portal,21/03/2025,Audited,Underpayment,155470,68269072,Low,82,Kaduna South,Yes
868,869,100534,KAD-TIN-202500868,Brown-Perez,Timothy Taylor,SME,Retail,Kubau,31/01/2024,2025,...,Portal,02/04/2024,Not Audited,Underpayment,96460,29335507,High,94,Kaduna North,No
197,198,100487,KAD-TIN-202500197,Mitchell Group,Jessica Perez,SME,Agriculture,Birnin Gwari,31/03/2025,2025,...,NGN,31/10/2025,Not Audited,Pending,179529,54730056,Low,37,Kaduna South,No
1613,1614,100071,KAD-TIN-202501613,"Ray, Sims and Mcdonald",David Delgado,Individual,Healthcare,Zangon Kataf,21/08/2024,2025,...,Bank Transfer,11/06/2025,Audited,Underpayment,54003,362876213,Low,74,Kaduna South,Yes

In [21]:
df.dtypes

record_id               int64
taxpayer_id             int64
tin                    object
business_name          object
owner_name             object
taxpayer_type          object
business_sector        object
lga                    object
registration_date      object
tax_year                int64
tax_month              object
tax_type               object
filing_due_date        object
filing_date            object
filing_status          object
amount_assessed         int64
amount_paid             int64
outstanding_balance     int64
payment_status         object
payment_method         object
payment_date           object
audit_status           object
audit_result           object
penalty                 int64
annual_turnover         int64
risk_level             object
compliance_score        int64
revenue_office         object
notification_sent      object
dtype: object

In [ ]:
Initial Dataset Observations

The dataset consists of approximately 2,000 records and 29 variables related to taxpayer registration, tax filing, payments, audits, and compliance metrics. Initial exploration shows a combination of numerical, categorical, and date variables. The dataset appears suitable for further analysis, although additional inspection will be carried out to identify missing values, duplicate records, inconsistent data entries, and incorrect data types before performing exploratory data analysis.